#Name: Aamir Khan Pathan
#File name: turtleflagsassignment.py
#date: 2025/0219
#File desciption: Assignment 1.2: Turtle Flags

# Import Turtle
import turtle

# Draw Japan Flag

  # Go To Starting Point
turtle.penup()
turtle.goto(-150,200)
turtle.pendown()

  # Begin Drawing Rectangle With Ratios Of 2:3
turtle.goto(150,200)
turtle.goto(150,0)
turtle.goto(-150,0)
turtle.goto(-150,200)

  # Send Turtle To Center For Japan Flag Circle (60 pixel radius)
turtle.penup()
turtle.pencolor('red')
turtle.goto(0,40)
turtle.pendown()
turtle.fillcolor('red')
turtle.begin_fill()
turtle.circle(60)
turtle.end_fill()

#Vietnam Flag

  # Go To  Bottom To Draw Rectangle
turtle.penup()
turtle.goto(-150,-200)
turtle.pendown()

  #Draw Rectangle Ratio 2:3
turtle.fillcolor('red')
turtle.pencolor('red')
turtle.begin_fill()
turtle.goto(150,-200)
turtle.goto(150,0)
turtle.goto(-150,0)
turtle.goto(-150,-200)
turtle.end_fill()
  
  #Go To Center And Draw Star
turtle.penup()
turtle.pencolor('yellow')
turtle.goto(50,-87.5)
turtle.fillcolor('yellow')
turtle.begin_fill()
turtle.right(144)
turtle.forward(100)
turtle.right(144)
turtle.forward(100)
turtle.right(144)
turtle.forward(100)
turtle.right(144)
turtle.forward(100)
turtle.right(144)
turtle.forward(100)
turtle.end_fill()
turtle.penup()
turtle.goto(0,0)
turtle.pendown()

#Reset Screen
turtle.reset()

#Draw Sweden Flag
  #Draw Outer Rectangle Ratio 5:8
turtle.penup()
turtle.pencolor('black')
turtle.goto(-160,200)
turtle.pendown()
turtle.fillcolor('blue')
turtle.begin_fill()
turtle.goto(160,200)
turtle.goto(160,0)
turtle.goto(-160,0)
turtle.goto(-160,200)
turtle.end_fill()
  # Draw Yellow Cross
turtle.pencolor('yellow')
turtle.penup()
turtle.goto(-160,120)
turtle.pendown()
turtle.fillcolor('yellow')
turtle.begin_fill()
turtle.goto(160,120)
turtle.goto(160,80)
turtle.goto(-160,80)
turtle.goto(-160,120)
turtle.end_fill()
turtle.penup()
turtle.goto(-60,200)
turtle.pendown()
turtle.fillcolor('yellow')
turtle.begin_fill()
turtle.goto(-20,200)
turtle.goto(-20,0)
turtle.goto(-60,0)
turtle.goto(-60,200)
turtle.end_fill()
turtle.pencolor('black')
# Flag Of France 2:3
  #Draw First Rectangle (Blue)
turtle.penup()
turtle.goto(-150,0)
turtle.pendown()
turtle.pencolor('blue')
turtle.fillcolor('blue')
turtle.begin_fill()
turtle.goto(-50,0)
turtle.goto(-50,-200)
turtle.goto(-150,-200)
turtle.goto(-150,0)
turtle.end_fill()
  #Draw Second Rectangle (White)
turtle.penup()
turtle.goto(-50,0)
turtle.pendown()
turtle.pencolor('black')
turtle.fillcolor('white')
turtle.begin_fill()
turtle.goto(50,0)
turtle.goto(50,-200)
turtle.goto(-50,-200)
turtle.goto(-50,0)
turtle.end_fill()
  # Draw Third Rectangle (Red)
turtle.penup()
turtle.goto(50,0)
turtle.pendown()
turtle.pencolor('red')
turtle.fillcolor('red')
turtle.begin_fill()
turtle.goto(150,0)
turtle.goto(150,-200)
turtle.goto(50,-200)
turtle.goto(50,0)
turtle.end_fill()
turtle.pencolor('black')
#Border
turtle.penup()
turtle.goto(-150,0)
turtle.pendown()
turtle.pensize(5)
turtle.goto(150,0)
turtle.goto(150,-200)
turtle.goto(-150,-200)
turtle.goto(-150,0)
# Clear Screen
turtle.reset()

# Flag Of Ireland 2:3
  #Draw First Rectangle (Green)
turtle.penup()
turtle.goto(-150,200)
turtle.pendown()
turtle.pencolor('green')
turtle.fillcolor('green')
turtle.begin_fill()
turtle.goto(-50,200)
turtle.goto(-50,0)
turtle.goto(-150,0)
turtle.goto(-150,200)
turtle.end_fill()
  #Draw Second Rectangle (White)
turtle.penup()
turtle.goto(-50,200)
turtle.pendown()
turtle.pencolor('black')
turtle.fillcolor('white')
turtle.begin_fill()
turtle.goto(50,200)
turtle.goto(50,0)
turtle.goto(-50,0)
turtle.goto(-50,200)
turtle.end_fill()
  # Draw Third Rectangle (Orange)
turtle.penup()
turtle.goto(50,200)
turtle.pendown()
turtle.pencolor('orange')
turtle.fillcolor('orange')
turtle.begin_fill()
turtle.goto(150,200)
turtle.goto(150,0)
turtle.goto(50,0)
turtle.goto(50,200)
turtle.end_fill()


# Flag Of Netherlands 2:3
  #Draw First Rectangle (Red)
turtle.penup()
turtle.goto(-150,0)
turtle.pendown()
turtle.pencolor('red')
turtle.fillcolor('red')
turtle.begin_fill()
turtle.goto(150,0)
turtle.goto(150,-200/3)
turtle.goto(-150,-200/3)
turtle.goto(-150,0)
turtle.end_fill()
  #Draw Second Rectangle (White)
turtle.penup()
turtle.goto(-150,-200/3)
turtle.pendown()
turtle.pencolor('black')
turtle.fillcolor('white')
turtle.begin_fill()
turtle.goto(150,-200/3)
turtle.goto(150,-400/3)
turtle.goto(-150,-400/3)
turtle.goto(-150,-200/3)
turtle.end_fill()
  # Draw Third Rectangle (Blue)
turtle.penup()
turtle.goto(-150,-400/3)
turtle.pendown()
turtle.pencolor('blue')
turtle.fillcolor('blue')
turtle.begin_fill()
turtle.goto(150,-400/3)
turtle.goto(150,-200)
turtle.goto(-150,-200)
turtle.goto(-150,-400/3)
turtle.end_fill()
#Border
turtle.pensize(5)
turtle.pencolor('black')
turtle.penup()
turtle.goto(-150,0)
turtle.pendown()
turtle.goto(150,0)
turtle.goto(150,-200)
turtle.goto(-150,-200)
turtle.goto(-150,0)
turtle.done()